### ISSUE TITLE
cellranger-analysis module: potential issue with dual genome reference

### ISSUE THREAD

**Issue by AntoniaChroni** [stjude-dnb-binfcore/sc-rna-seq-snap#26]
## What analysis module should be updated and why?

There might be an issue with the `cellranger-analysis` module when using dual genome reference. 

From our discussion with @sharonfreshour:

- The dual reference runs CellRanger's metrics include some that are specific to either the human or the mouse genomes used and those are labeled by CellRanger based on the reference name. For example, when the `summarize-cellranger-results.py` script is looking for a column named `mm10 ...`, it should be looking for a column named `GRCm39 ...` based on how CellRanger itself will name the metrics columns for the new GRCm39 reference.
 

## What changes need to be made? Please provide enough detail for another participant to make the update.

We will not make any changes for the moment.

**Comment by AntoniaChroni** [comment]
@CodyRamirez What are your thoughts on this?

**Comment by sharonfreshour** [comment]
Should we consider doing an additional test run of the module using the dual reference (similar to how we plan to do a test run with the human reference)?

**Comment by AntoniaChroni** [comment]
The current test dataset is one species (mouse). The [PR#30](https://github.com/stjude-dnb-binfcore/sc-rna-seq-snap/pull/30) using a genome reference from another species (human) serves to test and ensure that a different name and file path will not break the code. Testing for a dual genome reference will require the appropriate dataset. We can consider having such a dataset during the validation phase where we will explore different experiments and species.
